version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    Docker: 19 
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - eval $(aws ecr get-login --region ap-southeast-2 --no-include-email | sed 's|https://||'))
      - REPOSITORY_URI=287652358019.dkr.ecr.ap-south-1.amazonaws.com/testrepo
      - IMAGE_TAG=1.0
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker image ls -a
      - docker push $REPOSITORY_URI:$IMAGE_TAG
     
artifacts:
    files: imagedefinitions.json
   
